
import React, { useState, useCallback } from 'react';
import { SharedAstroSpot } from '@/lib/api/astroSpots';
import { usePhotoPointsMapContainer } from '@/hooks/photoPoints/usePhotoPointsMapContainer';
import MapContainer from './MapContainer';
import PageLoader from '@/components/loaders/PageLoader';

interface PhotoPointsMapProps {
  userLocation: { latitude: number; longitude: number } | null;
  locations: SharedAstroSpot[];
  certifiedLocations: SharedAstroSpot[];
  calculatedLocations: SharedAstroSpot[];
  activeView: 'certified' | 'calculated';
  searchRadius: number;
  onLocationClick?: (location: SharedAstroSpot) => void;
  onLocationUpdate?: (latitude: number, longitude: number) => void;
}

const PhotoPointsMap: React.FC<PhotoPointsMapProps> = (props) => { 
  const { 
    userLocation,
    locations,
    certifiedLocations,
    calculatedLocations,
    activeView,
    searchRadius,
    onLocationClick,
    onLocationUpdate
  } = props;
  
  // State for storing generated spots from SiqsEffectsController
  const [generatedSpots, setGeneratedSpots] = useState<SharedAstroSpot[]>([]);
  
  console.log(`PhotoPointsMap rendering - activeView: ${activeView}, locations: ${locations?.length || 0}, certified: ${certifiedLocations?.length || 0}, calculated: ${calculatedLocations?.length || 0}, generated: ${generatedSpots.length}`);
  
  const {
    mapContainerHeight,
    mapReady,
    handleMapReady,
    optimizedLocations,
    mapCenter,
    initialZoom,
    hoveredLocationId,
    handleHover,
    handleTouchStart,
    handleTouchEnd,
    handleTouchMove,
    handleMapClick,
    handleLocationClicked,
    handleGetLocation,
    handleLegendToggle,
    isMobile
  } = usePhotoPointsMapContainer({
    userLocation,
    locations: [...locations, ...generatedSpots],
    certifiedLocations,
    calculatedLocations: [...calculatedLocations, ...generatedSpots],
    activeView,
    searchRadius,
    onLocationClick,
    onLocationUpdate
  });
  
  // Handle spots generated by SiqsEffectsController
  const handleSpotsGenerated = useCallback((spots: SharedAstroSpot[]) => {
    console.log(`Received ${spots.length} generated spots to display on map`);
    setGeneratedSpots(prev => {
      // Only add spots that aren't already present (based on coords)
      const existingCoords = new Set(prev.map(spot => `${spot.latitude.toFixed(6)},${spot.longitude.toFixed(6)}`));
      const newSpots = spots.filter(spot => 
        !existingCoords.has(`${spot.latitude.toFixed(6)},${spot.longitude.toFixed(6)}`)
      );
      
      return [...prev, ...newSpots];
    });
  }, []);
  
  // Handle SIQS calculation from SiqsEffectsController
  const handleSiqsCalculated = useCallback((siqs: number) => {
    console.log(`Map center SIQS calculated: ${siqs.toFixed(1)}`);
  }, []);
  
  return (
    <MapContainer
      userLocation={userLocation}
      locations={optimizedLocations}
      searchRadius={searchRadius}
      activeView={activeView}
      mapReady={mapReady}
      handleMapReady={handleMapReady}
      handleLocationClicked={handleLocationClicked}
      handleMapClick={handleMapClick}
      mapCenter={mapCenter}
      initialZoom={initialZoom}
      mapContainerHeight={mapContainerHeight}
      isMobile={isMobile}
      hoveredLocationId={hoveredLocationId}
      handleHover={handleHover}
      handleTouchStart={handleTouchStart}
      handleTouchEnd={handleTouchEnd}
      handleTouchMove={handleTouchMove}
      handleGetLocation={handleGetLocation}
      onLegendToggle={handleLegendToggle}
      onSpotsGenerated={handleSpotsGenerated}
      onSiqsCalculated={handleSiqsCalculated}
    />
  );
};

export default PhotoPointsMap;
