-- Create countries table with flags
CREATE TABLE IF NOT EXISTS public.countries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL, -- ISO 3166-1 alpha-2 code
  name TEXT NOT NULL,
  name_zh TEXT, -- Chinese name
  flag_emoji TEXT NOT NULL, -- Unicode flag emoji
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.countries ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Countries are viewable by everyone"
  ON public.countries
  FOR SELECT
  USING (true);

-- Insert major countries with their flags
INSERT INTO public.countries (code, name, name_zh, flag_emoji) VALUES
  ('CN', 'China', '中国', '🇨🇳'),
  ('US', 'United States', '美国', '🇺🇸'),
  ('GB', 'United Kingdom', '英国', '🇬🇧'),
  ('JP', 'Japan', '日本', '🇯🇵'),
  ('KR', 'South Korea', '韩国', '🇰🇷'),
  ('FR', 'France', '法国', '🇫🇷'),
  ('DE', 'Germany', '德国', '🇩🇪'),
  ('IT', 'Italy', '意大利', '🇮🇹'),
  ('ES', 'Spain', '西班牙', '🇪🇸'),
  ('CA', 'Canada', '加拿大', '🇨🇦'),
  ('AU', 'Australia', '澳大利亚', '🇦🇺'),
  ('NZ', 'New Zealand', '新西兰', '🇳🇿'),
  ('BR', 'Brazil', '巴西', '🇧🇷'),
  ('MX', 'Mexico', '墨西哥', '🇲🇽'),
  ('AR', 'Argentina', '阿根廷', '🇦🇷'),
  ('CL', 'Chile', '智利', '🇨🇱'),
  ('IN', 'India', '印度', '🇮🇳'),
  ('RU', 'Russia', '俄罗斯', '🇷🇺'),
  ('ZA', 'South Africa', '南非', '🇿🇦'),
  ('EG', 'Egypt', '埃及', '🇪🇬'),
  ('AE', 'United Arab Emirates', '阿联酋', '🇦🇪'),
  ('SA', 'Saudi Arabia', '沙特阿拉伯', '🇸🇦'),
  ('TR', 'Turkey', '土耳其', '🇹🇷'),
  ('TH', 'Thailand', '泰国', '🇹🇭'),
  ('VN', 'Vietnam', '越南', '🇻🇳'),
  ('ID', 'Indonesia', '印度尼西亚', '🇮🇩'),
  ('MY', 'Malaysia', '马来西亚', '🇲🇾'),
  ('SG', 'Singapore', '新加坡', '🇸🇬'),
  ('PH', 'Philippines', '菲律宾', '🇵🇭'),
  ('PK', 'Pakistan', '巴基斯坦', '🇵🇰'),
  ('BD', 'Bangladesh', '孟加拉国', '🇧🇩'),
  ('NP', 'Nepal', '尼泊尔', '🇳🇵'),
  ('LK', 'Sri Lanka', '斯里兰卡', '🇱🇰'),
  ('MM', 'Myanmar', '缅甸', '🇲🇲'),
  ('KH', 'Cambodia', '柬埔寨', '🇰🇭'),
  ('LA', 'Laos', '老挝', '🇱🇦'),
  ('MN', 'Mongolia', '蒙古', '🇲🇳'),
  ('KZ', 'Kazakhstan', '哈萨克斯坦', '🇰🇿'),
  ('UZ', 'Uzbekistan', '乌兹别克斯坦', '🇺🇿'),
  ('AF', 'Afghanistan', '阿富汗', '🇦🇫'),
  ('IQ', 'Iraq', '伊拉克', '🇮🇶'),
  ('IR', 'Iran', '伊朗', '🇮🇷'),
  ('IL', 'Israel', '以色列', '🇮🇱'),
  ('JO', 'Jordan', '约旦', '🇯🇴'),
  ('LB', 'Lebanon', '黎巴嫩', '🇱🇧'),
  ('SY', 'Syria', '叙利亚', '🇸🇾'),
  ('YE', 'Yemen', '也门', '🇾🇪'),
  ('OM', 'Oman', '阿曼', '🇴🇲'),
  ('KW', 'Kuwait', '科威特', '🇰🇼'),
  ('QA', 'Qatar', '卡塔尔', '🇶🇦'),
  ('BH', 'Bahrain', '巴林', '🇧🇭'),
  ('AT', 'Austria', '奥地利', '🇦🇹'),
  ('BE', 'Belgium', '比利时', '🇧🇪'),
  ('BG', 'Bulgaria', '保加利亚', '🇧🇬'),
  ('HR', 'Croatia', '克罗地亚', '🇭🇷'),
  ('CY', 'Cyprus', '塞浦路斯', '🇨🇾'),
  ('CZ', 'Czech Republic', '捷克', '🇨🇿'),
  ('DK', 'Denmark', '丹麦', '🇩🇰'),
  ('EE', 'Estonia', '爱沙尼亚', '🇪🇪'),
  ('FI', 'Finland', '芬兰', '🇫🇮'),
  ('GR', 'Greece', '希腊', '🇬🇷'),
  ('HU', 'Hungary', '匈牙利', '🇭🇺'),
  ('IE', 'Ireland', '爱尔兰', '🇮🇪'),
  ('LV', 'Latvia', '拉脱维亚', '🇱🇻'),
  ('LT', 'Lithuania', '立陶宛', '🇱🇹'),
  ('LU', 'Luxembourg', '卢森堡', '🇱🇺'),
  ('MT', 'Malta', '马耳他', '🇲🇹'),
  ('NL', 'Netherlands', '荷兰', '🇳🇱'),
  ('NO', 'Norway', '挪威', '🇳🇴'),
  ('PL', 'Poland', '波兰', '🇵🇱'),
  ('PT', 'Portugal', '葡萄牙', '🇵🇹'),
  ('RO', 'Romania', '罗马尼亚', '🇷🇴'),
  ('SK', 'Slovakia', '斯洛伐克', '🇸🇰'),
  ('SI', 'Slovenia', '斯洛文尼亚', '🇸🇮'),
  ('SE', 'Sweden', '瑞典', '🇸🇪'),
  ('CH', 'Switzerland', '瑞士', '🇨🇭'),
  ('UA', 'Ukraine', '乌克兰', '🇺🇦'),
  ('BY', 'Belarus', '白俄罗斯', '🇧🇾'),
  ('MD', 'Moldova', '摩尔多瓦', '🇲🇩'),
  ('RS', 'Serbia', '塞尔维亚', '🇷🇸'),
  ('BA', 'Bosnia and Herzegovina', '波黑', '🇧🇦'),
  ('MK', 'North Macedonia', '北马其顿', '🇲🇰'),
  ('AL', 'Albania', '阿尔巴尼亚', '🇦🇱'),
  ('ME', 'Montenegro', '黑山', '🇲🇪'),
  ('KE', 'Kenya', '肯尼亚', '🇰🇪'),
  ('TZ', 'Tanzania', '坦桑尼亚', '🇹🇿'),
  ('UG', 'Uganda', '乌干达', '🇺🇬'),
  ('ET', 'Ethiopia', '埃塞俄比亚', '🇪🇹'),
  ('GH', 'Ghana', '加纳', '🇬🇭'),
  ('NG', 'Nigeria', '尼日利亚', '🇳🇬'),
  ('MA', 'Morocco', '摩洛哥', '🇲🇦'),
  ('TN', 'Tunisia', '突尼斯', '🇹🇳'),
  ('DZ', 'Algeria', '阿尔及利亚', '🇩🇿'),
  ('LY', 'Libya', '利比亚', '🇱🇾'),
  ('SD', 'Sudan', '苏丹', '🇸🇩'),
  ('BW', 'Botswana', '博茨瓦纳', '🇧🇼'),
  ('NA', 'Namibia', '纳米比亚', '🇳🇦'),
  ('ZW', 'Zimbabwe', '津巴布韦', '🇿🇼'),
  ('ZM', 'Zambia', '赞比亚', '🇿🇲'),
  ('MZ', 'Mozambique', '莫桑比克', '🇲🇿'),
  ('PE', 'Peru', '秘鲁', '🇵🇪'),
  ('CO', 'Colombia', '哥伦比亚', '🇨🇴'),
  ('VE', 'Venezuela', '委内瑞拉', '🇻🇪'),
  ('EC', 'Ecuador', '厄瓜多尔', '🇪🇨'),
  ('BO', 'Bolivia', '玻利维亚', '🇧🇴'),
  ('PY', 'Paraguay', '巴拉圭', '🇵🇾'),
  ('UY', 'Uruguay', '乌拉圭', '🇺🇾'),
  ('CR', 'Costa Rica', '哥斯达黎加', '🇨🇷'),
  ('PA', 'Panama', '巴拿马', '🇵🇦'),
  ('GT', 'Guatemala', '危地马拉', '🇬🇹'),
  ('HN', 'Honduras', '洪都拉斯', '🇭🇳'),
  ('NI', 'Nicaragua', '尼加拉瓜', '🇳🇮'),
  ('SV', 'El Salvador', '萨尔瓦多', '🇸🇻'),
  ('BZ', 'Belize', '伯利兹', '🇧🇿'),
  ('IS', 'Iceland', '冰岛', '🇮🇸'),
  ('GL', 'Greenland', '格陵兰', '🇬🇱'),
  ('FO', 'Faroe Islands', '法罗群岛', '🇫🇴'),
  ('AX', 'Åland Islands', '奥兰群岛', '🇦🇽')
ON CONFLICT (code) DO NOTHING;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_countries_code ON public.countries(code);